name: 百度搜索引擎URL提交

on:
  schedule:
    # 每周一和周四的凌晨3点执行
    - cron: '0 3 * * 1,4'
  # 允许手动触发
  workflow_dispatch:

jobs:
  submit-urls:
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        
      - name: 设置Node.js环境
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: 安装依赖
        run: npm ci
        
      - name: 执行百度URL提交脚本
        run: npm run baidu-submit
        
      - name: 提交结果通知
        if: always()
        uses: actions/github-script@v6
        with:
          script: |
            const { job, conclusion } = context;
            const status = conclusion === 'success' ? '✅ 成功' : '❌ 失败';
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## 百度URL提交结果: ${status}\n\n提交时间: ${new Date().toLocaleString('zh-CN', { timeZone: 'Asia/Shanghai' })}`
            }); 